"""Initial migration

Revision ID: d1e4b47d18fc
Revises: 
Create Date: 2024-10-01 11:52:14.889393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e4b47d18fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('to_trade', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conId', sa.Integer(), nullable=True),
    sa.Column('spread_around_spot', sa.Float(), nullable=True),
    sa.Column('lastTradeDateOrContractMonth', sa.Date(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('right', sa.String(), nullable=True),
    sa.Column('underlying_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['underlying_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conId')
    )
    op.create_table('economic_data_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economic_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('economic_data_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['economic_data_group_id'], ['economic_data_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('order_size', sa.Float(), nullable=False),
    sa.Column('order_price', sa.Float(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('order_exit_price', sa.Float(), nullable=True),
    sa.Column('bid_at_entry', sa.Float(), nullable=False),
    sa.Column('ask_at_entry', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('bar_size', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('trend', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_bars')
    op.drop_table('orders')
    op.drop_table('economic_data')
    op.drop_table('economic_data_groups')
    op.drop_table('contracts')
    # ### end Alembic commands ###
